---
title: "MAPP_baseline_results"
author: "Phoebe.Woodworth-Jefcoats@noaa.gov"
date: "2024-03-02"
output: html_document
---

## Baseline Results
This script put together some summary results and figures from the baseline _therMizer_ runs.

Set up the environment:
```{r}
# Load libraries
library(mizer)
library(here)
library("remotes")
remotes::install_github("sizespectrum/therMizer")
library("therMizer")
library("nmfspalette")
```

Load the baseline simulations:
```{r}
# This is a little tedious, but I'm not sure of a better way
load(here("FishingForcing", "DataFiles", "LENS_1_baseline.Rdata"))
sim_LENS_1 <- projection_steady_F
rm(projection_steady_F)
load(here("FishingForcing", "DataFiles", "LENS_2_baseline.Rdata"))
sim_LENS_2 <- projection_steady_F
rm(projection_steady_F)
load(here("FishingForcing", "DataFiles", "LENS_3_baseline.Rdata"))
sim_LENS_3 <- projection_steady_F
rm(projection_steady_F)
load(here("FishingForcing", "DataFiles", "LENS_4_baseline.Rdata"))
sim_LENS_4 <- projection_steady_F
rm(projection_steady_F)
load(here("FishingForcing", "DataFiles", "LENS_5_baseline.Rdata"))
sim_LENS_5 <- projection_steady_F
rm(projection_steady_F)
load(here("FishingForcing", "DataFiles", "LENS_6_baseline.Rdata"))
sim_LENS_6 <- projection_steady_F
rm(projection_steady_F)
load(here("FishingForcing", "DataFiles", "LENS_7_baseline.Rdata"))
sim_LENS_7 <- projection_steady_F
rm(projection_steady_F)
load(here("FishingForcing", "DataFiles", "LENS_8_baseline.Rdata"))
sim_LENS_8 <- projection_steady_F
rm(projection_steady_F)
load(here("FishingForcing", "DataFiles", "LENS_9_baseline.Rdata"))
sim_LENS_9 <- projection_steady_F
rm(projection_steady_F)
load(here("FishingForcing", "DataFiles", "LENS_10_baseline.Rdata"))
sim_LENS_10 <- projection_steady_F
rm(projection_steady_F)
```

Yield-at-size
```{r}
# Write a function to get yield by number at size
# This borrowed from other mizer functions
getYieldSize <- function(object) {
  no_sp <- nrow(object@params@species_params)
  min_w <- rep(min(object@params@w),no_sp)
  max_w <- rep(max(object@params@w),no_sp)
  
  min_n <- plyr::aaply(min_w, 1, function(x) object@params@w >= x, .drop = FALSE)
  max_n <- plyr::aaply(max_w, 1, function(x) object@params@w <= x, .drop = FALSE)
  size_range <- min_n & max_n
  dimnames(size_range) <- list(sp = object@params@species_params$species, 
                             w = signif(object@params@w, 3)) 
  
	if (is(object, "MizerSim")) {
		sim <- object
		n_at_size <- sweep(sim@n, c(2,3), size_range, '*')
		f_gear <- getFMortGear(sim)
		f_gear_sz <- sweep(f_gear, c(3,4),size_range,'*')
		yield_gear_species_size <- sweep(f_gear_sz, c(1,3,4), n_at_size,'*')
		return(apply(yield_gear_species_size,c(1,3,4),sum))
	}
	stop("'object' should be a MizerSim object")
}
```

Calculate biomass, abundance, and yield over time for each species and ensemble member:
```{r}
# time x species x ensemble member
EnsembleBiomass = array(NA, dim = c(87, 12, 10))
EnsembleN = array(NA, dim = c(87, 12, 10))
EnsembleYield = array(NA, dim = c(87, 12, 10))
# time x species x size x ensemble member
EnsembleNatSz <- array(NA, dim = c(87, 12, 100, 10))
EnsembleYieldSize <- array(NA, dim = c(87, 12, 100, 10))
# time x size x ensemble member
EnsembleNPP <- array(NA, dim = c(87, 226, 10))

# I'm sure there's a better way to do this, but I haven't worked it out.
EnsembleBiomass[,,1] <- getBiomass(sim_LENS_1)
EnsembleBiomass[,,2] <- getBiomass(sim_LENS_2)
EnsembleBiomass[,,3] <- getBiomass(sim_LENS_3)
EnsembleBiomass[,,4] <- getBiomass(sim_LENS_4)
EnsembleBiomass[,,5] <- getBiomass(sim_LENS_5)
EnsembleBiomass[,,6] <- getBiomass(sim_LENS_6)
EnsembleBiomass[,,7] <- getBiomass(sim_LENS_7)
EnsembleBiomass[,,8] <- getBiomass(sim_LENS_8)
EnsembleBiomass[,,9] <- getBiomass(sim_LENS_9)
EnsembleBiomass[,,10] <- getBiomass(sim_LENS_10)

EnsembleN[,,1] <- getN(sim_LENS_1)
EnsembleN[,,2] <- getN(sim_LENS_2)
EnsembleN[,,3] <- getN(sim_LENS_3)
EnsembleN[,,4] <- getN(sim_LENS_4)
EnsembleN[,,5] <- getN(sim_LENS_5)
EnsembleN[,,6] <- getN(sim_LENS_6)
EnsembleN[,,7] <- getN(sim_LENS_7)
EnsembleN[,,8] <- getN(sim_LENS_8)
EnsembleN[,,9] <- getN(sim_LENS_9)
EnsembleN[,,10] <- getN(sim_LENS_10)

EnsembleYield[,,1] <- getYield(sim_LENS_1)
EnsembleYield[,,2] <- getYield(sim_LENS_2)
EnsembleYield[,,3] <- getYield(sim_LENS_3)
EnsembleYield[,,4] <- getYield(sim_LENS_4)
EnsembleYield[,,5] <- getYield(sim_LENS_5)
EnsembleYield[,,6] <- getYield(sim_LENS_6)
EnsembleYield[,,7] <- getYield(sim_LENS_7)
EnsembleYield[,,8] <- getYield(sim_LENS_8)
EnsembleYield[,,9] <- getYield(sim_LENS_9)
EnsembleYield[,,10] <- getYield(sim_LENS_10)

EnsembleNatSz[,,,1] <- sim_LENS_1@n
EnsembleNatSz[,,,2] <- sim_LENS_2@n
EnsembleNatSz[,,,3] <- sim_LENS_3@n
EnsembleNatSz[,,,4] <- sim_LENS_4@n
EnsembleNatSz[,,,5] <- sim_LENS_5@n
EnsembleNatSz[,,,6] <- sim_LENS_6@n
EnsembleNatSz[,,,7] <- sim_LENS_7@n
EnsembleNatSz[,,,8] <- sim_LENS_8@n
EnsembleNatSz[,,,9] <- sim_LENS_9@n
EnsembleNatSz[,,,10] <- sim_LENS_10@n

EnsembleYieldSize[,,,1] <- getYieldSize(sim_LENS_1)
EnsembleYieldSize[,,,2] <- getYieldSize(sim_LENS_2)
EnsembleYieldSize[,,,3] <- getYieldSize(sim_LENS_3)
EnsembleYieldSize[,,,4] <- getYieldSize(sim_LENS_4)
EnsembleYieldSize[,,,5] <- getYieldSize(sim_LENS_5)
EnsembleYieldSize[,,,6] <- getYieldSize(sim_LENS_6)
EnsembleYieldSize[,,,7] <- getYieldSize(sim_LENS_7)
EnsembleYieldSize[,,,8] <- getYieldSize(sim_LENS_8)
EnsembleYieldSize[,,,9] <- getYieldSize(sim_LENS_9)
EnsembleYieldSize[,,,10] <- getYieldSize(sim_LENS_10)

EnsembleNPP[,,1] <- sim_LENS_1@n_pp
EnsembleNPP[,,2] <- sim_LENS_2@n_pp
EnsembleNPP[,,3] <- sim_LENS_3@n_pp
EnsembleNPP[,,4] <- sim_LENS_4@n_pp
EnsembleNPP[,,5] <- sim_LENS_5@n_pp
EnsembleNPP[,,6] <- sim_LENS_6@n_pp
EnsembleNPP[,,7] <- sim_LENS_7@n_pp
EnsembleNPP[,,8] <- sim_LENS_8@n_pp
EnsembleNPP[,,9] <- sim_LENS_9@n_pp
EnsembleNPP[,,10] <- sim_LENS_10@n_pp
```

Make some figures:
```{r}
# Access some handy info
species <- sim_LENS_1@params@species_params$species
size <- sim_LENS_1@params@w
year <- seq(2016, 2100, 1)
full_size <- sim_LENS_1@params@w_full

# Create a color palette
pal <- nmfs_palette("oceans")(10)

# Species in rank order of catch
species_order <- c(11,1,2,3,4,5,6,12,8,7,9,10)

# pdf(here("Figures", "BaselineBiomass.pdf"))
par(pin = c(1,1))
par(mfrow = c(2,6))
for (sp in species_order) {
	for (m in seq(1,10,1)) {
	  plot(year, (EnsembleBiomass[3:87, sp, m] - EnsembleBiomass[2, sp, m]) /  EnsembleBiomass[2, sp, m] * 100, 
	       type = "l", lwd = 2, col = pal[m], 
	       xlim = c(2016, 2100), ylim = c(-25, 25), xlab = " ", ylab = " ")
		par(new = TRUE)
	}
	plot(c(2016,2100),c(0,0), type = "l", col = "grey", 
	     xlim = c(2016,2100), ylim = c(-25 ,25), xlab = " ", ylab = " ", main = species[sp])
	axis((1), at = c(2016, 2020, 2040, 2060, 2080, 2100))
	axis((2), at = c(seq(-25, 25, 5)))
}
# dev.off()

# pdf(here("Figures", "BaselineYield.pdf"))
par(pin = c(1,1))
par(mfrow = c(2,6))
for (sp in species_order) {
	for (m in seq(1,10,1)) {
	  plot(year, (EnsembleYield[3:87, sp, m] - EnsembleYield[2, sp, m]) /  EnsembleYield[2, sp, m] * 100, 
	       type = "l", lwd = 2, col = pal[m], 
	       xlim = c(2016, 2100), ylim = c(-25, 25), xlab = " ", ylab = " ")
		par(new = TRUE)
	}
	plot(c(2016,2100),c(0,0), type = "l", col = "grey", 
	     xlim = c(2016,2100), ylim = c(-25 ,25), xlab = " ", ylab = " ", main = species[sp])
	axis((1), at = c(2016, 2020, 2040, 2060, 2080, 2100))
	axis((2), at = c(seq(-25, 25, 5)))
}
# dev.off()

# pdf(here("Figures", "BaselineN.pdf"))
par(pin = c(1,1))
par(mfrow = c(2,6))
for (sp in species_order) {
	for (m in seq(1,10,1)) {
	  plot(year, (EnsembleN[3:87, sp, m] - EnsembleN[2, sp, m]) /  EnsembleN[2, sp, m] * 100, 
	       type = "l", lwd = 2, col = pal[m], 
	       xlim = c(2016, 2100), ylim = c(-25, 25), xlab = " ", ylab = " ")
		par(new = TRUE)
	}
	plot(c(2016,2100),c(0,0), type = "l", col = "grey", 
	     xlim = c(2016,2100), ylim = c(-25 ,25), xlab = " ", ylab = " ", main = species[sp])
	axis((1), at = c(2016, 2020, 2040, 2060, 2080, 2100))
	axis((2), at = c(seq(-25, 25, 5)))
}
# dev.off()

# pdf(here("Figures", "BaselineNatSz.pdf"))
par(pin = c(1,1))
par(mfrow = c(2,6))
for (sp in species_order) {
	for (m in seq(1,10,1)) {
	  plot(log10(size), (EnsembleNatSz[87, sp, , m] - EnsembleNatSz[2, sp, , m]) /  EnsembleNatSz[2, sp, , m] * 100, 
	       type = "l", lwd = 2, col = pal[m], 
	       xlim = c(-3, 5.7), ylim = c(-25, 25), xlab = " ", ylab = " ")
		par(new = TRUE)
	}
	plot(c(-3, 5.7),c(0,0), type = "l", col = "grey", 
	     xlim = c(-3, 5.7), ylim = c(-25 ,25), xlab = " ", ylab = " ", main = species[sp])
	axis((1), at = c(seq(-3, 5, 1), 5.7))
	axis((2), at = c(seq(-25, 25, 5)))
}
# dev.off()

# pdf(here("Figures", "BaselineYieldSize.pdf"))
par(pin = c(1,1))
par(mfrow = c(2,6))
for (sp in species_order) {
	for (m in seq(1,10,1)) {
	  plot(log10(size), (EnsembleYieldSize[87, sp, , m] - EnsembleYieldSize[2, sp, , m]) /  EnsembleYieldSize[2, sp, , m] * 100, 
	       type = "l", lwd = 2, col = pal[m], 
	       xlim = c(-3, 5.7), ylim = c(-25, 25), xlab = " ", ylab = " ")
		par(new = TRUE)
	}
	plot(c(-3, 5.7),c(0,0), type = "l", col = "grey", 
	     xlim = c(-3, 5.7), ylim = c(-25 ,25), xlab = " ", ylab = " ", main = species[sp])
	axis((1), at = c(seq(-3, 5, 1), 5.7))
	axis((2), at = c(seq(-25, 25, 5)))
}
# dev.off()

# pdf(here("Figures", "BaselineNPP.pdf"))
for (m in seq(1,10,1)) {
	  plot(log10(full_size), (EnsembleNPP[87, , m] - EnsembleNPP[2, , m]) /  EnsembleNPP[2, , m] * 100, 
	       type = "l", lwd = 2, col = pal[m], 
	       xlim = c(-14, 5.7), ylim = c(-25, 25), xlab = " ", ylab = " ")
		par(new = TRUE)
}
plot(c(-14, 5.7),c(0,0), type = "l", col = "grey", 
     xlim = c(-14, 5.7), ylim = c(-25 ,25), xlab = " ", ylab = " ")
axis((1), at = c(seq(-14, 5, 1), 5.7))
axis((2), at = c(seq(-25, 25, 5)))
# dev.off()

# pdf(here("Figures", "Key10members.pdf"))
display_nmfs_palette("oceans", 10)
# dev.off()
```