---
title: "Workflow_Temperature"
author: "Phoebe.Woodworth-Jefcoats@noaa.gov"
date: '2023-06-05'
output: 
  html_document:
    toc: true
    toc_float: 
      collapsed: false
      smooth_scroll: false
---

__Workflow for processing LENS data for use with therMizer__  
This document describes the workflow for preparing the LENS temperature data for use in `therMizer`.  
It includes prepping the temperature data itself (`ocean_temp_array`) as well as the two
temperature-related arrays used in `therMizer`: `vertical_migration_array` and `exposure_array`.  

The scripts mentioned are in ClimateForcing and ClimateForcing/Temperature.  Where possible, the data
files are in ClimateForcing/Temperature/DataFiles.  Some of the data files are too large to include in
this repository.

Most of this workflow happens in [R](https://www.r-project.org/).  A few steps use [PyFerret](https://ferret.pmel.noaa.gov/Ferret/) or [Matlab](https://www.mathworks.com/products/matlab.html). 
It's likely you could do the PyFerret steps in R.  I use PyFerret out of habit because it's a free
language built specifically to handle large gridded datasets. You could also probably do the Matlab 
part in R.  I just did it in Matlab out of habit.

## Data Access
LENS data were provided by a project collaborator.

World Ocean Atlas (WOA) data were accessed with the PyFerret script `access_WOA.jnl`. 

## Data Wrangling
The remaining steps take the big, three-dimensional files from the LENS and WOA and pare them down 
to what's used for the therMizer simulations.

### Clipping the geographic area of interest
The first data wrangling step was clipping out the area of interest from the WOA data for the 
regional model.  Because this area isn't rectangular, I made a mask using `AreaMask.Rmd`.  I clipped 
the area of interest from the World Ocean Atlas (WOA) data using the area mask and the PyFerret 
script `clip_WOA_to_HIregion_plusMask.jnl`.  Note that this step included regridding the area grid 
to the more coarse WOA grid prior to clipping.  This is because the area mask was built for an earlier
project that used a finer grid.

### Spatial aggregation
I used PyFerret to spatially aggregate the WOA data using `RealmTemp_ts_WOA.jnl`.  This is done in 
two steps. First, the data are vertically averaged within each grid cell.  Then, they are spatially
averaged over the area of interest.  

The LENS data were aggregated across rectangular subregions with Matlab using 
`SubregionCombine.mlx`.  The PyFerret script `RealmTemp_ts_LENS.jnl` was then used to vertically 
average temperature withing each grid cell and then spatially average temperature over the area of
interest.

### Formatting temperature data for therMizer
The WOA and LENS data were combined and formatted for `therMizer` using the R script
`Prep_TempRealms_therMizer.Rmd`.  The WOA data is used as a baseline.  The difference between the
experiment time steps (2016 - 2100) and 2015 is added to this baseline.  This is done for each 
realm, and all realms are concatonated in `LENS_ocean_temp_realm_array.dat`.

### Creating `vertical_migration` and `exposure` arrays
The `vertical_migration` and `exposure` arrays that are used to link temperature to fish in `therMizer`
were created using `SetUp_Realms.Rmd`.

## Final Products
This workflow results in the following files that are used as input for `therMizer`:  
* `LE2_###_ocean_temp_realm_array.dat`  
* `HIregion_vertial_migration_array.Rdata`  
* `HIregion_exposure_array.dat`
